### ISSUE TITLE
Processing Enums as strings breaks when using BFrozenEnums

### ISSUE THREAD

**Issue by ib-mlatin** [novant-io/jasper-n4#1]
When a enumerated value is using a BFrozenEnum type for the range, it breaks how you guys are processing enums. In Niagara, you need to use the native enum reading functions instead of processing the whole range as a string. I would recommend calling getFacets() on the point and use the BEnumRange directly.

You need to support all of the possible cases that Niagara can provide:

![image](https://github.com/novant-io/jasper-n4/assets/60354324/71a3c26f-1a77-4e53-9905-6be3e33d6d8c)

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 25
at java.lang.String.charAt(String.java:658)
at jasper.util.JasperUtil.parseEnumRange(JasperUtil.java:163)
at jasper.service.BJasperService.doRebuildIndex(BJasperService.java:155)
at auto.jasper_service_BJasperService.invoke(AutoGenerated)
at com.tridium.sys.schema.ComponentSlotMap.invoke(ComponentSlotMap.java:1893)
at com.tridium.sys.schema.ComponentSlotMap.invoke(ComponentSlotMap.java:1858)
at javax.baja.sys.BComponent.invoke(BComponent.java:1223)
at com.tridium.fox.sys.broker.BBrokerChannel.invoke(BBrokerChannel.java:1877)
at com.tridium.fox.sys.broker.BBrokerChannel.process(BBrokerChannel.java:245)
at com.tridium.fox.sys.BFoxConnection.process(BFoxConnection.java:452)
at com.tridium.fox.session.SessionDispatcher.dispatch(SessionDispatcher.java:84)
at com.tridium.fox.session.SessionDispatcher.run(SessionDispatcher.java:63)
at java.lang.Thread.run(Thread.java:748)
```

Testing data:

```
/Drivers/NiagaraNetwork/ChilMus2/points/AHUs/Level_4/$34$2dAHU$2d4/points/DHMD_MODE [control:EnumPoint] - {LOG_OFF=0,LOG_ON=1,LOG_NUL=255}
/Drivers/NiagaraNetwork/ChilMus2/points/AHUs/Level_4/$34$2dAHU$2d4/points/DPR_C [control:EnumPoint] - {Off=0,On=1}
/Drivers/NiagaraNetwork/ChilMus2/points/AHUs/Level_4/$34$2dAHU$2d4/points/ECON$2dEN [control:EnumPoint] - {Normal=0,Full$20Bypass=1}
/Drivers/NiagaraNetwork/ChilMus3/points/Level_L/VAV_1_8/points/BOXMODE [control:EnumPoint] - jciSupport:JciN2BoxModeEnum (fails here)
/Drivers/NiagaraNetwork/ChilMus2/points/AHUs/Level_4/$34$2dAHU$2d4/points/EF9_SCHED [control:EnumPoint] - {LOG_OFF=0,LOG_ON=1,LOG_NUL=255}
/Drivers/NiagaraNetwork/ChilMus2/points/AHUs/Level_4/$34$2dAHU$2d4/points/EF10_SCHED [control:EnumPoint] - {LOG_OFF=0,LOG_ON=1,LOG_NUL=255}
/Drivers/NiagaraNetwork/ChilMus2/points/AHUs/Level_4/$34$2dAHU$2d4/points/DI7_HW_AVAIL [control:EnumPoint] - {LOG_OFF=0,LOG_ON=1,LOG_NUL=255}
/Drivers/NiagaraNetwork/ChilMus2/points/AHUs/Level_4/$34$2dAHU$2d4/points/SF_OVRD [control:EnumPoint] - {Enum_0=0,Enum_1=1,Enum_2=2,Enum_3=3,Enum_4=4,Enum_5=5,Enum_6=6,Enum_7=7,Enum_8=8,Enum_9=9,Enum_10=10,Enum_11=11,Enum_12=12,Enum_13=13,Enum_14=14,Enum_15=15,Enum_16=16,Enum_17=17,Enum_18=18,Enum_19=19,Enum_20=20,Enum_21=21,Enum_22=22,Enum_23=23,Enum_24=24,Enum_25=25,Enum_26=26,Enum_27=27,Enum_28=28,Enum_29=29,Enum_30=30,Enum_31=31,Enum_32=32,Enum_33=33,Enum_34=34,Enum_35=35,Enum_36=36,Enum_37=37,Enum_38=38,Enum_39=39,Enum_40=40,Enum_41=41,Enum_42=42,Enum_43=43,Enum_44=44,Enum_45=45,Enum_46=46,Enum_47=47,Enum_48=48,Enum_49=49,Enum_50=50,Enum_51=51,Enum_52=52,Enum_53=53,Enum_54=54,Enum_55=55,Enum_56=56,Enum_57=57,Enum_58=58,Enum_59=59,Enum_60=60,Enum_61=61,Enum_62=62,Enum_63=63,Enum_64=64,Enum_65=65,Enum_66=66,Enum_67=67,Enum_68=68,Enum_69=69,Enum_70=70,Enum_71=71,Enum_72=72,Enum_73=73,Enum_74=74,Enum_75=75,Enum_76=76,Enum_77=77,Enum_78=78,Enum_79=79,Enum_80=80,Enum_81=81,Enum_82=82,Enum_83=83,Enum_84=84,Enum_85=85,Enum_86=86,Enum_87=87,Enum_88=88,Enum_89=89,Enum_90=90,Enum_91=91,Enum_92=92,Enum_93=93,Enum_94=94,Enum_95=95,Enum_96=96,Enum_97=97,Enum_98=98,Enum_99=99,Enum_100=100,Enum_101=101,Enum_102=102,Enum_103=103,Enum_104=104,Enum_105=105,Enum_106=106,Enum_107=107,Enum_108=108,Enum_109=109,Enum_110=110,Enum_111=111,Enum_112=112,Enum_113=113,Enum_114=114,Enum_115=115,Enum_116=116,Enum_117=117,Enum_118=118,Enum_119=119,Enum_120=120,Enum_121=121,Enum_122=122,Enum_123=123,Enum_124=124,Enum_125=125,Enum_126=126,Enum_127=127,Enum_128=128,Enum_129=129,Enum_130=130,Enum_131=131,Enum_132=132,Enum_133=133,Enum_134=134,Enum_135=135,Enum_136=136,Enum_137=137,Enum_138=138,Enum_139=139,Enum_140=140,Enum_141=141,Enum_142=142,Enum_143=143,Enum_144=144,Enum_145=145,Enum_146=146,Enum_147=147,Enum_148=148,Enum_149=149,Enum_150=150,Enum_151=151,Enum_152=152,Enum_153=153,Enum_154=154,Enum_155=155,Enum_156=156,Enum_157=157,Enum_158=158,Enum_159=159,Enum_160=160,Enum_161=161,Enum_162=162,Enum_163=163,Enum_164=164,Enum_165=165,Enum_166=166,Enum_167=167,Enum_168=168,Enum_169=169,Enum_170=170,Enum_171=171,Enum_172=172,Enum_173=173,Enum_174=174,Enum_175=175,Enum_176=176,Enum_177=177,Enum_178=178,Enum_179=179,Enum_180=180,Enum_181=181,Enum_182=182,Enum_183=183,Enum_184=184,Enum_185=185,Enum_186=186,Enum_187=187,Enum_188=188,Enum_189=189,Enum_190=190,Enum_191=191,Enum_192=192,Enum_193=193,Enum_194=194,Enum_195=195,Enum_196=196,Enum_197=197,Enum_198=198,Enum_199=199,Enum_200=200,Enum_201=201,Enum_202=202,Enum_203=203,Enum_204=204,Enum_205=205,Enum_206=206,Enum_207=207,Enum_208=208,Enum_209=209,Enum_210=210,Enum_211=211,Enum_212=212,Enum_213=213,Enum_214=214,Enum_215=215,Enum_216=216,Enum_217=217,Enum_218=218,Enum_219=219,Enum_220=220,Enum_221=221,Enum_222=222,Enum_223=223,Enum_224=224,Enum_225=225,Enum_226=226,Enum_227=227,Enum_228=228,Enum_229=229,Enum_230=230,Enum_231=231,Enum_232=232,Enum_233=233,Enum_234=234,Enum_235=235,Enum_236=236,Enum_237=237,Enum_238=238,Enum_239=239,Enum_240=240,Enum_241=241,Enum_242=242,Enum_243=243,Enum_244=244,Enum_245=245,Enum_246=246,Enum_247=247,Enum_248=248,Enum_249=249,Enum_250=250,Enum_251=251,Enum_252=252,Enum_253=253,Enum_254=254,Enum_255=255}
/Drivers/NiagaraNetwork/ChilMus2/points/AHUs/Level_4/$34$2dAHU$2d4/points/DH1_OVRD [control:EnumPoint] - {Enum_0=0,Enum_1=1,Enum_2=2,Enum_3=3,Enum_4=4,Enum_5=5,Enum_6=6,Enum_7=7,Enum_8=8,Enum_9=9,Enum_10=10,Enum_11=11,Enum_12=12,Enum_13=13,Enum_14=14,Enum_15=15,Enum_16=16,Enum_17=17,Enum_18=18,Enum_19=19,Enum_20=20,Enum_21=21,Enum_22=22,Enum_23=23,Enum_24=24,Enum_25=25,Enum_26=26,Enum_27=27,Enum_28=28,Enum_29=29,Enum_30=30,Enum_31=31,Enum_32=32,Enum_33=33,Enum_34=34,Enum_35=35,Enum_36=36,Enum_37=37,Enum_38=38,Enum_39=39,Enum_40=40,Enum_41=41,Enum_42=42,Enum_43=43,Enum_44=44,Enum_45=45,Enum_46=46,Enum_47=47,Enum_48=48,Enum_49=49,Enum_50=50,Enum_51=51,Enum_52=52,Enum_53=53,Enum_54=54,Enum_55=55,Enum_56=56,Enum_57=57,Enum_58=58,Enum_59=59,Enum_60=60,Enum_61=61,Enum_62=62,Enum_63=63,Enum_64=64,Enum_65=65,Enum_66=66,Enum_67=67,Enum_68=68,Enum_69=69,Enum_70=70,Enum_71=71,Enum_72=72,Enum_73=73,Enum_74=74,Enum_75=75,Enum_76=76,Enum_77=77,Enum_78=78,Enum_79=79,Enum_80=80,Enum_81=81,Enum_82=82,Enum_83=83,Enum_84=84,Enum_85=85,Enum_86=86,Enum_87=87,Enum_88=88,Enum_89=89,Enum_90=90,Enum_91=91,Enum_92=92,Enum_93=93,Enum_94=94,Enum_95=95,Enum_96=96,Enum_97=97,Enum_98=98,Enum_99=99,Enum_100=100,Enum_101=101,Enum_102=102,Enum_103=103,Enum_104=104,Enum_105=105,Enum_106=106,Enum_107=107,Enum_108=108,Enum_109=109,Enum_110=110,Enum_111=111,Enum_112=112,Enum_113=113,Enum_114=114,Enum_115=115,Enum_116=116,Enum_117=117,Enum_118=118,Enum_119=119,Enum_120=120,Enum_121=121,Enum_122=122,Enum_123=123,Enum_124=124,Enum_125=125,Enum_126=126,Enum_127=127,Enum_128=128,Enum_129=129,Enum_130=130,Enum_131=131,Enum_132=132,Enum_133=133,Enum_134=134,Enum_135=135,Enum_136=136,Enum_137=137,Enum_138=138,Enum_139=139,Enum_140=140,Enum_141=141,Enum_142=142,Enum_143=143,Enum_144=144,Enum_145=145,Enum_146=146,Enum_147=147,Enum_148=148,Enum_149=149,Enum_150=150,Enum_151=151,Enum_152=152,Enum_153=153,Enum_154=154,Enum_155=155,Enum_156=156,Enum_157=157,Enum_158=158,Enum_159=159,Enum_160=160,Enum_161=161,Enum_162=162,Enum_163=163,Enum_164=164,Enum_165=165,Enum_166=166,Enum_167=167,Enum_168=168,Enum_169=169,Enum_170=170,Enum_171=171,Enum_172=172,Enum_173=173,Enum_174=174,Enum_175=175,Enum_176=176,Enum_177=177,Enum_178=178,Enum_179=179,Enum_180=180,Enum_181=181,Enum_182=182,Enum_183=183,Enum_184=184,Enum_185=185,Enum_186=186,Enum_187=187,Enum_188=188,Enum_189=189,Enum_190=190,Enum_191=191,Enum_192=192,Enum_193=193,Enum_194=194,Enum_195=195,Enum_196=196,Enum_197=197,Enum_198=198,Enum_199=199,Enum_200=200,Enum_201=201,Enum_202=202,Enum_203=203,Enum_204=204,Enum_205=205,Enum_206=206,Enum_207=207,Enum_208=208,Enum_209=209,Enum_210=210,Enum_211=211,Enum_212=212,Enum_213=213,Enum_214=214,Enum_215=215,Enum_216=216,Enum_217=217,Enum_218=218,Enum_219=219,Enum_220=220,Enum_221=221,Enum_222=222,Enum_223=223,Enum_224=224,Enum_225=225,Enum_226=226,Enum_227=227,Enum_228=228,Enum_229=229,Enum_230=230,Enum_231=231,Enum_232=232,Enum_233=233,Enum_234=234,Enum_235=235,Enum_236=236,Enum_237=237,Enum_238=238,Enum_239=239,Enum_240=240,Enum_241=241,Enum_242=242,Enum_243=243,Enum_244=244,Enum_245=245,Enum_246=246,Enum_247=247,Enum_248=248,Enum_249=249,Enum_250=250,Enum_251=251,Enum_252=252,Enum_253=253,Enum_254=254,Enum_255=255}
/Drivers/NiagaraNetwork/ChilMus2/points/AHUs/Level_4/$34$2dAHU$2d4/points/EF9_C [control:EnumPoint] - {LOG_OFF=0,LOG_ON=1,LOG_NUL=255}
/Drivers/NiagaraNetwork/ChilMus2/points/AHUs/Level_4/$34$2dAHU$2d4/points/EF10_C [control:EnumPoint] - {LOG_OFF=0,LOG_ON=1,LOG_NUL=255}
```

**Comment by afrankvt** [comment]
I believe this has been fixed in https://github.com/novant-io/jasper-n4/commit/2dbc25a7d8782536013f756db6667fc104c145f2 and available in the latest `0.12` release?

(Note that we do not report the integer mappings back into Jasper at this point (because the spec grammar needs to be updated first).  But as the values are always `floats` this should not effect the API endpoints)

That stack trace looks like it's from a previous release?

**Comment by ib-mlatin** [comment]
My mistake, yeah looks like I missed that commit. This was from a version that was tested on May 31st. I'll run some more tests to make sure and if it's unrelated, I'll open another issue.

**Comment by afrankvt** [comment]
No problem - yes, please let me know if it's still not right!
